# Header
menu :
  主页    : /
  相册    : /photos
  #随笔    : "http://123.206.18.105"

# SubNav
subnav:
  weibo         : "http://weibo.com/Nundy"
  mail          : "mailto:18710939328@163.com"
  github        : "https://github.com/UniqueSirius"
  wangyiyun     : "https://music.163.com/m/user/home?id=274111924"
  rss           : "/atom.xml"
  #qq           : "http://wpa.qq.com/msgrd?v=3&uin=3053915949&site=qq&menu=yes"
  #jianshu      : "http://www.jianshu.com/users/ba1556fea564/timeline"
  #zhihu        : ""
  #douban       : ""
  #segmentfault : ""
  #bilibili     : ""
  #acfun        : ""
  #facebook     : "#"
  #google       : "#"
  #twitter      : "#"
  #linkedin     : "#"

#RSS订阅
rss       : /atom.xml

#sitemap站点地图
sitemap   : /sitemap.xml

#URL主页链接设置
url       : http://uniquesoli.cn
root      : /

# Content设置
excerpt_link        : false        # 文章太长，截断按钮文字，不需要请设置为false
show_all_link       : '展开全文'  # 文章卡片右下角常驻链接，不需要请设置为false
mathjax             : false       # 数学公式
open_in_new         : false       # 是否在新窗口打开链接

# 打赏
reward_type         : 1 # 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_wording      : '小伙子可以啊，有前途！' # 打赏wording
weixin              : /assets/img/weixin.png # 微信二维码图片地址
alipay              : # 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg

# 目录

toc                 : 1 # 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc_hide_index      : true # 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_empty_wording   : '目录? 不存在的…' # 目录为空时的提示
top                 : true # 是否有快速回到顶部的按钮

# Miscellaneous站点统计
baidu_analytics     : 'true'
google_analytics    : ''

#站点logo
favicon   : /assets/img/favicon.png

#头像
avatar    : /assets/img/Coding.jpg

#是否开启分享
share_jia       : true

#评论系统 : 畅言
changyan_appid  :  'cytabldO0' 
changyan_conf   :  'prod_beb9be0e55a353aec8701c62b6a3fe0b'

# 样式定制
style :
  header    : '#4d4d4d' # 头像上面的背景颜色
  slider    : 'linear-gradient(200deg,#6DD0B9,#EB7F52)' # 右滑板块背景

# slider的设置
slider :
  showTags   : true # 是否默认展开tags板块

# 智能菜单
smart_menu :
  innerArchive    : '所有文章'
  friends         : 'Demo'
  aboutme         : '关于我'

friends   :
  Test    : http://localhost:4000/

aboutme   : 如果有来生<br/><br/>要做一棵树<br/><br/>站成永恒<br/><br/>没有悲欢的姿势<br/><br/>一半在土里安详<br/><br/>一半在风里飞扬<br/><br/>一半洒落阴凉<br/><br/>一半沐浴阳光<br/><br/>非常沉默，非常骄傲<br/><br/>从不依靠，从不寻找<br/><br/>